/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controle.de.qualidade;


/**
 *
 * @author davys_000
 */
public class MenuCliente extends javax.swing.JFrame {

    /**
     * Creates new form MenuCliente
     */
    public MenuCliente(Cliente tempc) {
        String temp;
        c = tempc;
        initComponents();
        jLabel4.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        temp = c.getCpf();
        numCPF.setText(temp.substring(0,3)+"."+temp.substring(3,6)+"."+temp.substring(6,9)+"-"+temp.substring(9,11));
    }

    private MenuCliente() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        cpfLalbel = new javax.swing.JLabel();
        numCPF = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        comboLabel = new javax.swing.JLabel();
        select = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cpfLalbel1 = new javax.swing.JLabel();
        numCPF1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        comboLabel1 = new javax.swing.JLabel();
        select1 = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jPanel4.setLayout(new java.awt.GridLayout(3, 0));

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        cpfLalbel.setText("CPF:");
        cpfLalbel.setAlignmentY(0.8F);
        jPanel8.add(cpfLalbel);

        numCPF.setForeground(new java.awt.Color(220, 38, 38));
        numCPF.setText("cpf");
        jPanel8.add(numCPF);

        jPanel4.add(jPanel8);

        comboLabel.setText("Selecione a Avaliação:");
        jPanel6.add(comboLabel);

        select.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"", "Compras", "Oficina", "Atendimento"}));
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        jPanel6.add(select);

        jPanel4.add(jPanel6);

        jLabel2.setText("jLabel1");
        jPanel7.add(jLabel2);

        jLabel3.setText("Oficina");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel3);

        jLabel4.setText("jLabel6");
        jPanel7.add(jLabel4);

        jPanel4.add(jPanel7);

        jTabbedPane1.addTab("Fazer Avaliação", jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(3, 0));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        cpfLalbel1.setText("CPF:");
        cpfLalbel1.setAlignmentY(0.8F);
        jPanel1.add(cpfLalbel1);

        numCPF1.setForeground(new java.awt.Color(220, 38, 38));
        numCPF1.setText("cpf");
        jPanel1.add(numCPF1);

        jPanel5.add(jPanel1);

        comboLabel1.setText("Selecione a Avaliação:");
        jPanel9.add(comboLabel1);

        select1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"", "Compras", "Oficina", "Atendimento"}));
        select1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select1ActionPerformed(evt);
            }
        });
        jPanel9.add(select1);

        jPanel5.add(jPanel9);

        jLabel5.setText("jLabel1");
        jPanel10.add(jLabel5);

        jLabel6.setText("Oficina");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel6);

        jLabel7.setText("jLabel6");
        jPanel10.add(jLabel7);

        jPanel5.add(jPanel10);

        jTabbedPane1.addTab("Visualizar Avaliação", jPanel5);

        getContentPane().add(jTabbedPane1);

        setSize(new java.awt.Dimension(416, 381));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        // TODO add your handling code here:

        int opc;

        opc = select.getSelectedIndex();

        if (opc == 0) {
            jLabel4.setVisible(false);
            jLabel2.setVisible(false);
            jLabel2.setVisible(false);
        } else if (opc == 1) {
            jLabel4.setVisible(false);
            jLabel3.setVisible(false);
            jLabel2.setVisible(true);
        } else if (opc == 2) {
            jLabel2.setVisible(false);
            jLabel4.setVisible(false);
            jLabel3.setVisible(true);
        } else if (opc == 3) {
            jLabel3.setVisible(false);
            jLabel2.setVisible(false);
            jLabel4.setVisible(true);
        }
    }//GEN-LAST:event_selectActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Avaliacao m = new Avaliacao();
        m.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void select1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel comboLabel;
    private javax.swing.JLabel comboLabel1;
    private javax.swing.JLabel cpfLalbel;
    private javax.swing.JLabel cpfLalbel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel numCPF;
    private javax.swing.JLabel numCPF1;
    private javax.swing.JComboBox select;
    private javax.swing.JComboBox select1;
    // End of variables declaration//GEN-END:variables
    private Cliente c;
}
